var i18n = new Array();

i18n['de'] = {
  'Downloads'    : 'Download',
  'Support'      : 'Unterstützung',
  'Community'    : 'Community',
  'Development'  : 'Entwicklung',
  'Sign up'      : 'Anmelden', 
  'Login'        : 'Einloggen',
  'Username'     : 'Benutzername',
  'Password'     : 'Passwort',
  'Search'       : 'Suche',
  'openSUSE Explained': 'openSUSE erklärt',
  'Experienced Users' : 'Erfahrene Benutzer',
  
  'openSUSE 12.1 Portal'    : 'openSUSE 12.1 Portal',
  ': The information portal about your distribution.' : ': das Informationsportal zu Deiner Distribution',
  'See why openSUSE 12.1 is cool: The' : 'Warum openSUSE 12.1 cool ist: Die ',
  'product highlights'      : 'Produkt-Highlights',
  'Learn more about the different ways to' : 'Erfahre mehr über die verschiedenen Wege ',
  'install openSUSE'        : 'openSUSE zu installieren',
  'Coming from another OS? These are the' : 'Kommst Du von einem anderen OS? Dies sind die ',
  'Application Equivalents' : 'alternativen Programme',
  
  'Community is key for openSUSE' : 'Community ist die Hauptsache',
  'Learn how'               :'Lerne wie ',
  'the project'             : 'das Projekt ',
  'is set up.'              : 'aufgesetzt ist',
  'openSUSE is carried on by various' : 'openSUSE wird entwickelt von verschiedenen ',
  'Teams'                   : 'Teams',
  'openSUSE is yours: See'  : 'openSUSE gehört Dir: ',
  'how to participate.'     : 'Mach mit!',
  'Join the openSUSE social platform': 'Trete openSUSE\'s sozialem Netzwerk bei: ',
  'Connect'                 : 'Die Connect Platform',
  
  'You want more?'          : 'Willst Du mehr?',
  'More'                    : 'Mehr ',
  'documentation in depth'  : 'Dokumentation',
  'Even more'               : 'Noch mehr ',
  'Software'                : 'Programme',
  'A'                       : 'Ein ',
  'bleeding edge system'    : 'System mit den neuesten Neuerungen',
  'Ready-to-use Images from' : 'Fertige Abbilder aus ',
  'SUSE-Studio'             : 'SUSE Studio',
  
  'Bugs and Features'       : 'Fehler und Funktionen ',
  
  'All about our tool'      : 'Alles über unser Werkzeug ' ,
  'Bugzilla'                : 'Bugzilla',
  'The important'           : 'Die wichtigen ',
  'Bugreporting FAQ'        : 'Fragen zum Fehler reporten',
  'The most annoying'       : 'Die nervigsten ',
  'Bugs'                    : 'Fehler',
  'Work on'                 : 'Arbeit an ',
  'features'                : 'Funktionen',
  'in the'                  : ' im ',
  'screening team'          : 'Feature-Screening Team',
  
  'Stay in touch'           : 'In Kontakt bleiben',
  'Read blogs on the'       : 'Lese Blogs auf ',
  'openSUSE Planet'         : 'openSUSE Planet',
  'Interesting'             : 'Interessante ',
  'feeds around the project.': 'Feeds rund um das Projekt.',
  'News and Announcements'  : 'Neuigkeiten und Ankündigungen',
  'Effective Communication on' : 'Effektive Kommunikation auf ',
  'Mailinglists'            : 'Mailinglisten',
  
  'Contribute'              : 'Mitarbeiten',
  'People active worldwide: The' : 'Aktive Leute weltweit: Die ',
  'openSUSE Ambassadors'    : 'openSUSE Botschafter',
  'Tell about it:'          : 'Rede drüber: ',
  'openSUSE Marketing'      : 'openSUSE Marketing',
  'Make it appealing: Help on' : 'Mach es hübsch: Helfe den ',
  'openSUSE Artwork'        : 'openSUSE Künstlern',
  'Work in the'             : 'Arbeite in der ',
  'Factory'                 : 'Fabrik',
  'and improve the next openSUSE release.' : ' und verbessere die nächsten Ausgabe.'
};


